### ISSUE TITLE
vgm_cmp error for using DCSG VGM

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#11]
[vgm_cmp.zip](https://github.com/vgmrips/vgmtools/files/6322313/vgm_cmp.zip)
These files in the compressed package cannot be compressed using vgm_cmp.

**Comment by ValleyBell** [comment]
hmm ... it gets confused by the lack of EoF command in those files.

How did you manage to create such files?

**Comment by denjhang** [comment]
I used the wav2psg provided in a post on the sms power! forum more than ten years ago for conversion
[wav to psg.zip](https://github.com/vgmrips/vgmtools/files/6322991/wav.to.psg.zip)
.

**Comment by ValleyBell** [comment]
Okay, interesting.

Anyway, a675dd892357146d90a8cb6fc27a87d7d28ec6ae fixes the crash.
It doesn't really "fix" the files though (i.e. they will still lack the EOF offset) and it seems to eat up the last wait command in the file.

**Comment by denjhang** [comment]
So how do I add EOF to the vgm?

**Comment by ValleyBell** [comment]
You add a byte `66` with a hex editor to the end of the file.
Then you increase the "EOF offset" in the VGM header (offset 0x04..0x07) by 1.
