### ISSUE TITLE
vgm2txt running abnormally

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#25]
[nrtdrv-vgm.zip](https://github.com/vgmrips/vgmtools/files/10301116/nrtdrv-vgm.zip)
After I tried, I found that all the vgm in this compressed package cannot be converted to txt correctly. These vgm use dual OPM+PSG.

**Comment by ValleyBell** [comment]
Fixed with by commit dc31d645d4dc675ea6c7ac5b7a5944df4692012e.

The reason of the crash was incorrect handling of the AY8910 type. It would crash due to the "YM2149" subtype.
