### ISSUE TITLE
Use vgm_txt for YM2612 VGM, get many DAC = 80

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#29]
0x00031059: 52 2A 80    YM2612:		DAC = 80
0x0003105C: 73          Wait:	 4 sample(s) (   0.09 ms)	(total	158245 (00:03.59))
0x0003105D: 52 2A 80    YM2612:		DAC = 80
0x00031060: 73          Wait:	 4 sample(s) (   0.09 ms)	(total	158249 (00:03.59))
0x00031061: 52 2A 80    YM2612:		DAC = 80
0x00031064: 73          Wait:	 4 sample(s) (   0.09 ms)	(total	158253 (00:03.59))

I recorded VGM using blastem, I don't know if this is normal or not. Because it seems so confusing. I won't be able to find a starting point for VGM.

**Comment by b0x-Cub3d** [comment]
That's normal, however if you can strip out the DAC/FM5 channel via vgm_ptch to make the disassembly a bit eligible. Just make sure to keep the original log on you since you can't get that data back after stripping it.

**Comment by ValleyBell** [comment]
The game's sound driver probably does a constant PCM stream, which is the reason for the regular DAC commands.

vgm2txt will not filter anything. Everything works as intended.
