### ISSUE TITLE
vgm2txt does not work as expected

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#32]
![sshot-20240730-000941](https://github.com/user-attachments/assets/c98ca5a2-c4b7-4ff3-aaaa-ad958373107c)
I only want it to output the first 2 seconds of the vgm, but it always outputs the entire thing.

**Comment by denjhang** [comment]
`echo off
for /f "tokens=1 delims=." %%a in ('dir *.vgm /b') do (call:myFuncHasPara %%a) 

pause



:myFuncHasPara
echo %1.vgm
vgm2txt "%1.vgm" 0 0:02.0
goto:eof
`

**Comment by ValleyBell** [comment]
I have no idea what goes wrong for you there. This works just fine here.

![vgm2txt](https://github.com/user-attachments/assets/af4daf6d-b5da-4c7e-92c2-1f60e2a6a4e6)

**Comment by denjhang** [comment]
![sshot-20240730-002255](https://github.com/user-attachments/assets/9c08201f-0377-4e1d-ad64-bec021ea4bdf)

**Comment by denjhang** [comment]
Is it only allowed to input line by line? I am batch trimming some VGMs. This does not happen when I use vgm_trim. It would be much simpler if vgm2txt could input the sample values ​​directly.

**Comment by denjhang** [comment]
I often use complex bat to process vgm files with no problems when using vgm_trim. This is most likely that bat is bad at handling special symbols.

**Comment by ValleyBell** [comment]
No, your syntax above is definitely supposed to work.

To me it looks like it somehow fails to parse the number and I don't understand why.
Maybe `sscanf` doesn't work properly on your system? (vgm_trim uses a different function that supports only raw numbers, but in vgm2txt I use "formatted parsing".)

**Comment by denjhang** [comment]
Version problem or compiler problem. The exe I used to compile with vc6 or cygwin cannot execute sscanf correctly. The exe you posted has no problem.

**Comment by denjhang** [comment]
[VGMTools_2022-12-30.zip](https://github.com/user-attachments/files/16416231/VGMTools_2022-12-30.zip)
This is the currently available version.
