### ISSUE TITLE
small bug in vgm2txt YM2151 TEST register 0x01

### ISSUE THREAD

**Issue by vampirefrog** [vgmrips/vgmtools#5]
Hello. For YM2151, the second bit (mask 0x02) of the 0x01 TEST register is called LFO Reset, not LFO On/Off as vgm2txt outputs.

http://img.vampi.tech/089c07b3.png

**Comment by superctr** [comment]
That bit in the register also resets the lfo and that's what it is usually
used for. So I don't consider it a bug.

Den 16 nov. 2017 10:28 em skrev "vampirefrog" <notifications@github.com>:

**Comment by superctr** [comment]
And vice versa of course, the lfo is turned off as long as the bit is set.

Den 16 nov. 2017 10:55 em skrev "Ian Karlsson" <themvrules@gmail.com>:

**Comment by superctr** [comment]
[https://github.com/mamedev/mame/blob/master/src/devices/sound/ym2151.txt](MAME docs) actually call the bit "HLFO". Apparently the LFO is halted at max amplitude when the bit is set, and when it is cleared (from being set), then the LFO is reset.

**Comment by vampirefrog** [comment]
MXDRV writes 1 then 0 to that bit in order to reset the LFO phase. The YM151 User Manual calls it "LFO RESET". I suppose vgm2txt could output:
54 01 02    YM2151:		Test Register, LFO Halt (max amplitude)
54 01 00    YM2151:		Test Register, LFO Reset
Ideally, vgm2txt would remember the last LFO Halt and call it a 'reset' only then, otherwise calling it 'unexpected'. Either way, "LFO Off" is incorrect for when the bit is zero, as is "LFO On" incorrect for when the bit is set.

**Comment by ValleyBell** [comment]
Fixed by d60d736e6ad18259ed8b8ac9ea1f54c8b3b299fb.
